### ISSUE TITLE
启动网易云时提示脚本运行但是不能播放无版权歌曲

### ISSUE THREAD

**Issue by T9041** [nining377/dolby_beta#39]
如题，两个文件的路径都对，但就是不能放歌

**Comment by liuhaofay** [comment]
同上，网易云7.31，lsposed 安卓11

**Comment by nining377** [comment]
打开网易云的时候提示unm运行成功了吗？

**Comment by liuhaofay** [comment]
提示运行成功，但是无法播放，无版权，灰色

**Comment by nining377** [comment]
> 提示运行成功，但是无法播放，无版权，灰色

日志中有关于大喇叭的错误吗？

**Comment by liuhaofay** [comment]
这个没看诶，我又给换成老版本了

**Comment by nining377** [comment]
好吧，你可以试试新版本

**Comment by nining377** [comment]
> 这个没看诶，我又给换成老版本了

好吧，你可以试试大喇叭的新版本

**Comment by aviraxp** [comment]
2.0.1 + 网易云 8.1.50 同样错误。日志没有任何打印，从 logcat 看 hook 是正常加载的

**Comment by aviraxp** [comment]
查看了node与脚本均正确解压，node 也正常运行， 但仍然提示无版权

**Comment by nining377** [comment]
> 查看了node与脚本均正确解压，node 也正常运行， 但仍然提示无版权

请告知是哪首歌

**Comment by aviraxp** [comment]
所有没版权的歌。。。。

**Comment by nining377** [comment]
> 所有没版权的歌。。。。

(๑òᆺó๑)啊这，那有没有开了梯子一类的东西呢？

**Comment by aviraxp** [comment]
关了梯子也一样。。。。

**Comment by nining377** [comment]
> 关了梯子也一样。。。。

8.1.50我只在模拟器上试过，我去用真机试试

**Comment by aviraxp** [comment]
但是UnblockMusicPro可用

**Comment by nining377** [comment]
> 但是UnblockMusicPro可用

这就很神奇，不过你在启用杜比大喇叭代理的是否关闭了UMP呢？我这边测试并没能复现，更新到最新版后是可以正常播放无音源歌曲的

**Comment by aviraxp** [comment]
关了

**Comment by aviraxp** [comment]
我用ump放歌到一半然后切换成大喇叭，发现这首歌可以继续下载剩下的一般并播放，但在切歌后再换回来就不行了，说明下歌的部分是没问题的

**Comment by nining377** [comment]
> 我用ump放歌到一半然后切换成大喇叭，发现这首歌可以继续下载剩下的一般并播放，但在切歌后再换回来就不行了，说明下歌的部分是没问题的

暂时无法定位问题，先标记为bug吧，下个版本增加一个脚本日志打印开关，到时候你再来试试看日志里打印了什么

**Comment by aviraxp** [comment]
`3-16 13:36:11.218 I/LSPosed ( 4029): Loading modules for com.netease.cloudmusic
03-16 13:36:11.218 I/LSPosed-Bridge( 4029): Loading modules from /data/app/~~MvjMRq8MvuL5VPYQBAZemg==/com.raincat.dolby_beta-rF9kgZoZvjCIXqo-dLSDRw==/base.apk
03-16 13:36:11.237 I/LSPosed-Bridge( 4029):   Loading class com.raincat.dolby_beta.MainHook
03-16 13:36:11.240 E/ANDR-RAMBOOST_SERVER( 1391): ramboost cmd_len = 126 cmd: iop_start -1 com.netease.cloudmusic /data/app/~~Y2LIcveGC57ZBZAG1eoczw==/com.netease.cloudmusic-cFDoY8V1KyEBH62r-AbG-w== false
03-16 13:36:11.246 I/DisplayPowerController( 1739): useProximityForceSuspend = false
03-16 13:36:11.247 D/OnePlusDuallteManager( 1739): notifyFrontPkgToLlmController :com.netease.cloudmusic
03-16 13:36:11.247 I/RampAnimator( 1739): target:0.7655007 rate:0.7058823 mCurrentValue:0.7607907 mTargetValue:0.7655007
03-16 13:36:11.247 D/OnePlusDuallteManager( 1739): notifyFrontPkgToLlmController setLLMPackageName :com.netease.cloudmusic
03-16 13:36:11.248 D/OpLowLatencyModeController( 3313): setLLMPackageName getFrontPackageName = com.netease.cloudmusic
03-16 13:36:11.248 E/ANDR-RAMBOOST_SERVER( 1391): ramboost cmd_len = 128 cmd: iop_start 4029 com.netease.cloudmusic /data/app/~~Y2LIcveGC57ZBZAG1eoczw==/com.netease.cloudmusic-cFDoY8V1KyEBH62r-AbG-w== false
03-16 13:36:11.248 W/QC_RIL_OEM_HOOK( 3313): getNrMode phoneId: 1
03-16 13:36:11.248 D/OpProximityController( 1739): noteFrontPackageChanged pkg:com.netease.cloudmusic uid:10333 lpkg:net.oneplus.launcher luid:10153
03-16 13:36:11.249 D/OemSceneModeActivityStack( 1739): [scene] evaluateGameModes :  gameMsg.arg1=0 gameMsg.arg2=1
03-16 13:36:11.249 D/surfaceflinger( 1093): [frame_perf] config pid[5337]
03-16 13:36:11.249 D/surfaceflinger( 1093): [frame_perf] config app[net.oneplus.launcher]
03-16 13:36:11.249 D/surfaceflinger( 1093): [frame_perf] config state pause
03-16 13:36:11.251 D/QcrilMsgTunnelIfaceManager( 2993): handleMessage what = 1
03-16 13:36:11.251 I/QcrilOemhookMsgTunnel( 2993): [1]invokeOemRilRequestRaw: serial=1794 length=28
03-16 13:36:11.251 E/ScreenModeService( 1739): getAppToken ActivityRecord{5d20aa u0 com.netease.cloudmusic/.activity.LoadingActivity t6571}
03-16 13:36:11.251 E/ScreenModeService( 1739): setRefreshRate token ActivityRecord{5d20aa u0 com.netease.cloudmusic/.activity.LoadingActivity t6571} rate 0 tmpRate 0
03-16 13:36:11.251 D/OpQuickReply( 1739): setQuickReplyResumed focusedApp ActivityRecord{5d20aa u0 com.netease.cloudmusic/.activity.LoadingActivity t6571} pkgName com.netease.cloudmusic
03-16 13:36:11.251 W/OpBacklightController( 1739): animateScreenBrightness: percent=0.92, minNits=200.0, maxBrightness=0.99, adjustBrightnessIntervalNits=50.0
03-16 13:36:11.252 I/DisplayPowerController( 1739): useProximityForceSuspend = false
03-16 13:36:11.252 I/DisplayPowerController( 1739): smtbrn:0.92 0.7655007 (257.49) --> 0.73601145(237.06248)
03-16 13:36:11.252 I/DisplayPowerController( 1739): rate:0.01238963
03-16 13:36:11.252 I/RampAnimator( 1739): target:0.73601145 rate:0.01238963 mCurrentValue:0.7607907 mTargetValue:0.7655007
03-16 13:36:11.252 I/RampAnimator( 1739): G:660 preS:5 S:5 target:0.73601145 mCurrentValue:0.7607907 rate:0.01238963 mIsSystemUIOrSetting:false
03-16 13:36:11.252 E/Parcel  ( 6466): Reading a NULL string not supported here.
03-16 13:36:11.252 E/horae   ( 6466): setForegroundPackage, mChargingStateMachine is null!
03-16 13:36:11.264 I/QcrilOemhookMsgTunnel( 2993): [1]processOemHookResponse serial no: 1794 error: 0length=1
03-16 13:36:11.264 D/QcrilMsgTunnelIfaceManager( 2993): handleMessage what = 2
03-16 13:36:11.266 D/QC_RIL_OEM_HOOK( 3313): sendOemRilRequestRaw returns value = 1
03-16 13:36:11.266 D/QC_RIL_OEM_HOOK( 3313): getNrMode, nrMode: 0
03-16 13:36:11.267 D/ApplicationLoaders( 4029): Returning zygote-cached class loader: /system/framework/android.test.base.jar
03-16 13:36:11.269 I/ease.cloudmusi( 4029): The ClassLoaderContext is a special shared library.
03-16 13:36:11.274 D/StatusBar( 2664): Status bar WINDOW_STATE_HIDDEN
03-16 13:36:11.274 D/KeyguardAffordanceView( 2664): setCircleRadius: 0.0com.android.systemui.statusbar.KeyguardAffordanceView.setCircleRadiusWithoutAnimation:416 com.android.systemui.statusbar.phone.KeyguardAffordanceHelper.updateIcon:444 com.android.systemui.statusbar.phone.KeyguardAffordanceHelper.setTranslation:394 com.android.systemui.statusbar.phone.KeyguardAffordanceHelper.reset:506 com.android.systemui.statusbar.phone.NotificationPanelViewController.resetViews:1200 com.android.systemui.statusbar.phone.PanelBar.collapsePanel:223 com.android.systemui.statusbar.phone.StatusBar.setWindowState:2587 
03-16 13:36:11.276 D/OverviewProxyService( 2664): SystemUi flags: 40000000
03-16 13:36:11.276 I/chatty  ( 5337): uid=10153(net.oneplus.launcher) Binder:5337_D expire 1 line
03-16 13:36:11.277 D/OverviewProxyService( 2664): SystemUi flags: 40000000
03-16 13:36:11.371 D/IOLIMITER( 3289): get message: change@/module/oneplus_healthinfo ACTION=change DEVPATH=/module/oneplus_healthinfo SUBSYSTEM=module OHMACTION=uevent OHMTYPE=iowait OHMLEVEL=LOW SEQNUM=11360 
03-16 13:36:11.372 D/IOLIMITER( 3289): dolimit with level: low
03-16 13:36:11.374 W/IOLIMITER( 3289): no records found
03-16 13:36:11.374 D/IOLIMITER( 3289): all lines of record read!
03-16 13:36:11.374 D/IOLIMITER( 3289): [switch] switch on
03-16 13:36:11.374 D/IOLIMITER( 3289): [switch] switch off after 2000 ms
03-16 13:36:11.374 D/IOLIMITER( 3289): Now will wait for the next uevent
03-16 13:36:11.374 D/IOLIMITER( 3289): enter the circle of wait for signal, waiting
03-16 13:36:11.389 I/100     ( 4029): Open /data/app/~~Y2LIcveGC57ZBZAG1eoczw==/com.netease.cloudmusic-cFDoY8V1KyEBH62r-AbG-w==/base.apk took:118ms
03-16 13:36:11.410 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.410 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.428 I/Perf    ( 4029): Connecting to perf service.
03-16 13:36:11.432 I/ease.cloudmusi( 4029): [GL_OOM] ClearGrowthLimit 536870912
03-16 13:36:11.432 I/ease.cloudmusi( 4029): [GL_OOM] limited APP ClearGrowthLimit, set size to 536870912
03-16 13:36:11.433 D/NetworkSecurityConfig( 4029): Using Network Security Config from resource e debugBuild: false
03-16 13:36:11.434 D/NetworkSecurityConfig( 4029): Using Network Security Config from resource e debugBuild: false
03-16 13:36:11.447 D/Tinker.TinkerLoader( 4029): tryLoad test test
03-16 13:36:11.448 W/Tinker.TinkerLoader( 4029): tryLoadPatchFiles:patch dir not exist:/data/user/0/com.netease.cloudmusic/tinker
03-16 13:36:11.448 D/Tinker.DefaultAppLike( 4029): onBaseContextAttached:
03-16 13:36:11.487 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.487 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.492 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.492 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.494 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.494 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.496 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.496 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.502 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.502 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.505 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.505 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.654 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.654 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.655 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.655 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.656 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.656 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.659 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.659 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.665 W/ease.cloudmusi( 4029): Unsupported class loader
03-16 13:36:11.665 W/ease.cloudmusi( 4029): Could not establish class loader context
03-16 13:36:11.673 D/OPBF    ( 1739): setCGroupState():tofreeze=true, uid:10303 pkg:com.antfortune.wealth --->>> ok reason:operateNode reconfirm lastOperation:false lastOperatedReason:start perform not hasTimeout broadcast for action = android.intent.action.PACKAGE_ADDED
03-16 13:36:11.697 V/OPConfig:ConfigProvider( 2626): Module:OnePlusFontConfig
03-16 13:36:11.698 E/Config:Grabber:OnePlusFontConfig( 4029): Index 0 requested, with a size of 0
03-16 13:36:11.698 D/Tinker.DefaultAppLike( 4029): onCreate
03-16 13:36:11.699 V/OPConfig:ConfigProvider( 2626): Module:OnePlusFontConfig
03-16 13:36:11.700 E/Config:Grabber:OnePlusFontConfig( 4029): Index 0 requested, with a size of 0
03-16 13:36:11.702 D/NeteaseMusicConst( 4029): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm|6040,2147483647
03-16 13:36:11.703 D/NeteaseMusicConst( 4029): scanWhitePaths:/storage/emulated/0/qqmusic/offline/
03-16 13:36:11.713 I/CM_DeepLink( 4029): {"channel":"tencent"}
03-16 13:36:11.713 D/NeteasePlayConst( 4029): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm|6040,2147483647
03-16 13:36:11.714 D/NeteasePlayConst( 4029): scanWhitePaths:/storage/emulated/0/qqmusic/offline/
03-16 13:36:11.728 W/System.err( 4029): java.lang.ClassNotFoundException: com.netease.cloudmusic.common.ViewHolderResourceConfig
03-16 13:36:11.729 W/System.err( 4029): 	at java.lang.Class.classForName(Native Method)
03-16 13:36:11.729 W/System.err( 4029): 	at java.lang.Class.forName(Class.java:454)
03-16 13:36:11.729 W/System.err( 4029): 	at java.lang.Class.forName(Class.java:379)
03-16 13:36:11.729 W/System.err( 4029): 	at com.netease.cloudmusic.common.nova.autobind.h.a(SourceFile:31)
03-16 13:36:11.729 W/System.err( 4029): 	at com.netease.cloudmusic.NeteaseMusicApplication.onCreate(SourceFile:268)
03-16 13:36:11.729 W/System.err( 4029): 	at com.netease.cloudmusic.core.patch.PatchApplicationLike.onCreate(SourceFile:36)
03-16 13:36:11.729 W/System.err( 4029): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(SourceFile:70)
03-16 13:36:11.729 W/System.err( 4029): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(SourceFile:59)
03-16 13:36:11.729 W/System.err( 4029): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(SourceFile:52)
03-16 13:36:11.729 W/System.err( 4029): 	at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(SourceFile:49)
03-16 13:36:11.729 W/System.err( 4029): 	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(SourceFile:165)
03-16 13:36:11.729 W/System.err( 4029): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
03-16 13:36:11.729 W/System.err( 4029): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6984)
03-16 13:36:11.729 W/System.err( 4029): 	at java.lang.reflect.Method.invoke(Native Method)
03-16 13:36:11.729 W/System.err( 4029): 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
03-16 13:36:11.729 W/System.err( 4029): 	at LspHooker_.handleBindApplication(Unknown Source:11)
03-16 13:36:11.730 W/System.err( 4029): 	at android.app.ActivityThread.access$1700(ActivityThread.java:274)
03-16 13:36:11.730 W/System.err( 4029): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
03-16 13:36:11.730 W/System.err( 4029): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-16 13:36:11.730 W/System.err( 4029): 	at android.os.Looper.loop(Looper.java:233)
03-16 13:36:11.730 W/System.err( 4029): 	at android.app.ActivityThread.main(ActivityThread.java:8007)
03-16 13:36:11.730 W/System.err( 4029): 	at java.lang.reflect.Method.invoke(Native Method)
03-16 13:36:11.730 W/System.err( 4029): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
03-16 13:36:11.730 W/System.err( 4029): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
03-16 13:36:11.730 W/System.err( 4029): Caused by: java.lang.ClassNotFoundException: com.netease.cloudmusic.common.ViewHolderResourceConfig
03-16 13:36:11.730 W/System.err( 4029): 	... 24 more`

**Comment by aviraxp** [comment]
03-16 13:35:55.491 W/ncat.dolby_bet( 9110): Unsupported class loader
03-16 13:35:55.491 W/ncat.dolby_bet( 9110): Could not establish class loader context

破案了？tinker背锅

**Comment by aviraxp** [comment]
[Uploading logcat.log…]()

**Comment by nining377** [comment]
> 03-16 13:35:55.491 W/ncat.dolby_bet( 9110): Unsupported class loader
> 03-16 13:35:55.491 W/ncat.dolby_bet( 9110): Could not establish class loader context
> 
> 破案了？tinker背锅

但是我已经删掉热修复的包，禁止他热修复了呀，你可以试试较低版本网易云

**Comment by aviraxp** [comment]
6.x依然不行，最神奇的是UMP可用

**Comment by nining377** [comment]
> 6.x依然不行，最神奇的是UMP可用

emmmmmm，你把日志清除了再打开网易云，看看还会不会有报错信息出来，还有脚本和node路径对了吗

**Comment by aviraxp** [comment]
貌似是这行判断的问题

https://github.com/nining377/dolby_beta/blob/790834f35392a35e32b8382258e1b9e80eb8b8af/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java#L71

将其按照旧版的黑名单逻辑

https://github.com/nining377/UnblockMusicPro_Xposed/blob/master/app/src/main/java/com/raincat/unblockmusicpro/HTTPHook.java#L160

修改即可收听，但貌似有些其他小问题，让我打个日志看看

**Comment by nining377** [comment]
> 貌似是这行判断的问题
> 
> https://github.com/nining377/dolby_beta/blob/790834f35392a35e32b8382258e1b9e80eb8b8af/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java#L71
> 
> 将其按照旧版的黑名单逻辑
> 
> https://github.com/nining377/UnblockMusicPro_Xposed/blob/master/app/src/main/java/com/raincat/unblockmusicpro/HTTPHook.java#L160
> 
> 修改即可收听，但貌似有些其他小问题，让我打个日志看看

UMP是用的黑名单模式，只是剔除了个别代理会不正常的URL其他全走代理，但是会导致所有无版权歌曲显示不正常，加上脚本作者太久不维护了会有一些奇奇怪怪的小问题，所以大喇叭换成了白名单模式，只代理歌曲播放和下载的URL

**Comment by aviraxp** [comment]
https://github.com/nining377/dolby_beta/pull/46

**Comment by aviraxp** [comment]
先别合，能听了但是无法下载

**Comment by nining377** [comment]
> 先别合，能听了但是无法下载

噗，合了…但是按理说只需要那两个url即可，对于无版权歌曲大喇叭已经处理并不需要UNM，所以，emmmmm，先加上吧，如果对你有帮助的话
